id: org.eclipse.che.vscode.yaml
version: 1.0.0
type: VS Code extension
name: k8s-plugin
title: YAML extension
description: YAML extension
icon: https://www.eclipse.org/che/images/ico/16x16.png
attributes:
  extension: "vscode:extension/redhat.vscode-yaml"
  container-image: "wsskeleton/theia-endpoint-runtime"
